version: "3.8"

services:
  aninbot:
    image: aninbot:latest
    # Build your image first: docker build -t aninbot:latest .
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Bind-mount local settings.py so you can edit it and restart the service
      - type: bind
        source: ${ANINBOT_SETTINGS_PATH}
        target: /app/settings.py
        read_only: true
      # Optional: mount a folder with assets if you use APPEARANCE.avatar_path
      # - type: bind
      #   source: ${ANINBOT_ASSETS_PATH}
      #   target: /app/assets
      #   read_only: true

